### ISSUE TITLE
Error: The non-abstract class 'MagicCredential' is missing implementations for these members:

### ISSUE THREAD

**Issue by qbirr** [magiclabs/magic-flutter#10]
Error: The non-abstract class 'MagicCredential' is missing implementations for these members:
../…/web3/magic_credential.dart:9
 - Credentials.signToEcSignature
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class MagicCredential extends CredentialsWithKnownAddress
      ^^^^^^^^^^^^^^^
: Context: 'Credentials.signToEcSignature' is defined here.
../…/credentials/credentials.dart:84
  MsgSignature signToEcSignature(

               ^^^^^^^^^^^^^^^^^

**Comment by Ethella** [comment]
Hi @qbirr, the fix has been merged, and there is some transitive dependencies issue that needs to be worked on before releasing the patch. Ideally, the fix will get published by the EOD. Thank you for your patience.
