### ISSUE TITLE
Upgrade webview_flutter package and web3dart

### ISSUE THREAD

**Issue by varunlohade** [magiclabs/magic-flutter#22]
Hey Team
I am getting this issue when I am trying to use magic

`Because magic_sdk >=2.0.2 depends on web3dart 2.5.1 and myapp depends on web3dart ^2.6.1, magic_sdk >=2.0.2 is forbidden.
So, because myapp depends on magic_sdk ^2.0.2, version solving failed.`

same issue with webview_flutter.
Some functionalities in webview_flutter are only available in the latest package of webview_flutter
Any fix for this

**Comment by Ariflo** [comment]
Hi @varunlohade, thanks for bringing this to our attention. We are investigating possible solutions and will update you asap.

**Comment by Ariflo** [comment]
@varunlohade give the latest version of our package a try and continue to let us know if you run into issues. Thanks!

**Comment by varunlohade** [comment]
Awesome, I will try and let you know about issues
Thanks
