### ISSUE TITLE
google OAuth login Error Could not process OAuth request because cookies are malformed, missing, or tampered with.

### ISSUE THREAD

**Issue by varunlohade** [magiclabs/magic-flutter#25]
![Screenshot_20230525-134500_Chrome](https://github.com/magiclabs/magic-flutter/assets/50517140/e7cc2155-3918-4270-82fd-ac8bfbc71045)

This is the issue I am facing

Could not process OAuth request because cookies are malformed, missing, or tampered with.

**Comment by Ariflo** [comment]
Hi again @varunlohade we'll take a look. In the meantime, verify that you've followed all [the correct steps](https://magic.link/docs/auth/login-methods/social-logins/integration/oauth-implementation/flutter) to get setup with the social login provider. This error often creeps up when something is missing on the social login provider's side.

**Comment by Ariflo** [comment]
Closing out as this issue is now stale.
