### ISSUE TITLE
Exception when launching App, LateInitialization Error: Field 'webViewCtrl' has not been initialized

### ISSUE THREAD

**Issue by varunlohade** [magiclabs/magic-flutter#26]
![Screenshot_20230525-135048](https://github.com/magiclabs/magic-flutter/assets/50517140/ff9f636d-f54e-4920-aa15-db89a234dd3f)

Error:
LateInitializationError: Field
'webViewctri' has not been initialized.

**Comment by Ariflo** [comment]
Thanks @varunlohade, we'll see about patching this one up as well.

**Comment by jigarfumakiya** [comment]
@Ariflo How soon can you guys fix this we need to upload the build to the production

**Comment by Ariflo** [comment]
@jigarfumakiya We've got this on our docket and are aiming to get it fixed before the end of next week.

**Comment by jigarfumakiya** [comment]
@Ariflo Try to fix it ASAP, Thanks!

**Comment by Ariflo** [comment]
@jigarfumakiya try now with `v3.0.1` Thanks!
