### ISSUE TITLE
Error on login - "Device requesting login is not supported. Please try again from a secure context."

### ISSUE THREAD

**Issue by kumarpalsinh25** [magiclabs/magic-flutter#31]
I'm not able to log in with email OTP from my Flutter app. It is giving the below error.

![Screenshot 2023-08-10 at 5 31 36 PM](https://github.com/magiclabs/magic-flutter/assets/51526480/fe3efa90-3bde-4770-bea9-db247bed997a)

I'm facing this error for the last 2 days, it was working fine before that. The code is the same.

**Comment by Ariflo** [comment]
Thank you for bringing this to our attention @kumarpalsinh25, we are aware of the issue and are working to resolve it asap.

**Comment by kumarpalsinh25** [comment]
Thanks @Ariflo for the quick response. 

Hopefully it will be resolved quickly as our production app users are facing difficulties in accessing app.

**Comment by Ariflo** [comment]
@kumarpalsinh25 we've just pushed out a patch, give it a look and let us know if you're still seeing the issue.

**Comment by kumarpalsinh25** [comment]
@Ariflo 
Looks fine now.

Thanks for quick resolution!

**Comment by WeiJun0507** [comment]
Hi, I encountered the same error in the Flutter application by using loginWithSMS and loginWithEmailOTP method. I used it two hours ago. May I know any solution I could make to let my login success?

**Comment by Ariflo** [comment]
@WeiJun0507 We are currently unable to reproduce the error described here as it has been resolved. For sanity check; have you tried force closing your flutter app, trying again?

**Comment by WeiJun0507** [comment]
Yes, I did try several times. I only get the dependencies last Friday and I am sure that everything is correct because I could sign in with google provider. But I kept getting this prompt when I try to login with SMS or email

**Comment by Ariflo** [comment]
@WeiJun0507, we can turn the device check off. Please contact our support via the widget in the bottom-right corner of our homepage on https://magic.link/ ?

Thank you!

**Comment by WeiJun0507** [comment]
> @WeiJun0507, we can turn the device check off. Please contact our support via the widget in the bottom-right corner of our homepage on https://magic.link/ ?
> 
> Thank you!

sure， will do. Thank you

**Comment by sebastiantf** [comment]
We are facing this on a web app being accessed from different devices including Mobile and Laptops

**Comment by Ariflo** [comment]
@sebastiantf You should be able to turn this security offering off on your Magic dashboard > Settings > Device Registration. 

![Screenshot 2023-10-10 at 9 05 32 AM](https://github.com/magiclabs/magic-flutter/assets/13407884/9c04aaff-d3ff-4a2c-9e15-0895051f9cae)

Otherwise, please contact our support team via the widget in the bottom-right corner of our homepage on https://magic.link/ and we'll do our best to resolve your concern in a timely manner.
