### ISSUE TITLE
App crash - Magic.instance.relayer - iOS

### ISSUE THREAD

**Issue by kumarpalsinh25** [magiclabs/magic-flutter#38]
The app crashes on the screen where we have added "Magic.instance.relayer" Widget.

- - - - -
**Scenario.**
- - - - -
**Home Screen:** 
- This screen contains login with a magic button

**Login Scree:**
- This screen contains the code for login with the magic link as per the given documentation.

`Stack(
      children: [
        magicAuthContentUI(context),
        Magic.instance.relayer
      ],
);`

Step 1: Open the Login Screen by clicking on the login button from the Home Screen.
Step 2: Close the Login Screen without doing anything and go back to the Home Screen.
Step 3: Now Open the Login Screen again and the app crashes at the "Magic.instance.relayer" code

- - - - -
**Flutter Doctor Data**
- - - - -
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] Network resources
• No issues found!

- - - - -
**Magic SDK Version** 
- - - - -
magic_sdk: ^4.0.0

Let me know if any other information is needed.

Looking forward to a quick resolution on the given issue.

Thanks

**Comment by Ariflo** [comment]
@kumarpalsinh25 I'm sorry to see you're running into this error. Please try updating to the latest version of the magic-sdk `v4.1.1` and running on an iOS device running iOS 14 or greater. If you continue to see the issue, try running it with our demo app. We currently are unable to reproduce the error with our demo app. Thanks!

**Comment by kumarpalsinh25** [comment]
Hello @Ariflo,

Thanks for your quick reply and for sharing your thoughts regarding the issue.

Unfortunately, the issue is still there even after using  magic-sdk v4.1.1.

I would like to share the screen recording & demo project code for your reference.

**Demo Project Code:**
[magic_sdk_demo.zip](https://github.com/magiclabs/magic-flutter/files/12445068/magic_sdk_demo.zip)

**Screen recording:**
https://github.com/magiclabs/magic-flutter/assets/51526480/569b92ed-cadc-41bb-a3f9-22c0bd2605d9

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-x64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

**Magic SDK:**
magic_sdk: ^4.1.1

**Note:**
The issue is only on iOS. The Android app is working fine with the same flutter code base.

Please go through the given details and do the needful to resolve the issue.

Let me know if more information is required.

Thanks

**Comment by kumarpalsinh25** [comment]
Hello @Ariflo,
Can you please help us with the resolution of the above iOS crash?

Let me know if you need any additional details.

**Comment by vtuscano** [comment]
@kumarpalsinh25 and @Ariflo - I found the issue. 

In: **/magic_sdk-4.1.2/lib/relayer/webview.dart** 
https://github.com/magiclabs/magic-flutter/blob/8bc9bf9ac5a0af98d254a1951ae21a087d9e2852/packages/magic_sdk/lib/relayer/webview.dart#L123

The function **loadWebView()** sets this JS Channel, but the issue is that sometimes it's already set, so you need to unset it:

### ADD THIS:
**widget._webViewCtrl.removeJavaScriptChannel("magicFlutter");**

So, change that group to:
```

widget._webViewCtrl.setJavaScriptMode(JavaScriptMode.unrestricted);
widget._webViewCtrl.removeJavaScriptChannel("magicFlutter");
widget._webViewCtrl.addJavaScriptChannel('magicFlutter',
        onMessageReceived: (JavaScriptMessage message) {
      onMessageReceived(message);
});
```

**Comment by Ariflo** [comment]
Thank you both, appreciate your patience as we look into this, we'll send out a patch today!
