### ISSUE TITLE
Doesn't work in Android Release mode

### ISSUE THREAD

**Issue by hmziqrs** [magiclabs/magic-flutter#43]
Hi, I've been trying to debug the issue but didn't have any success. No authentication-related method works in Android release mode but works fine in `Android (Debug)` and `iOS (Release and Debug)`. I've combed through the docs a few times but didn't see any `Android` related configuration I might've missed. I've also tried to build release APK from 2 MacBooks and 1 Window device.

Issue:
Async methods are not resolved or rejected they are stuck at loading.

Here's the demo app where you can test it:
https://github.com/basedapp/magic_link_android_debug

**Flutter Doctor**

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5 22G74 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!`

**Comment by Ariflo** [comment]
@hackerhgl Thank you for bringing this issue to our attention. Please consider updating your app's proguard-rules as we have done here: https://github.com/magiclabs/magic-flutter/pull/44 to bypass this error. Thanks 🙇

**Comment by hmziqrs** [comment]
@Ariflo Thank you. Add progard-rules fixed the issue. But please make this part of the documentation as well.
