### ISSUE TITLE
Unable to login using any of the available login methods on iOS Flutter

### ISSUE THREAD

**Issue by sleepersubject13** [magiclabs/magic-flutter#46]
I have been able to login using the available methods on both Android and iOS for  along time now. However, in the past few weeks, I realised I can only log in successfully on Android but not iOS. Basically, code execution gets stuck on this logic, for instance, using Google to sign in:

` final configuration = moauth.OAuthConfiguration(
        provider: moauth.OAuthProvider.GOOGLE,
        redirectURI: "${EnvironmentConfig.PACKAGE_NAME}://",
      );
      OAuthResponse response = await magic.oauth.loginWithPopup(configuration);`
      
 am however able to login successsfully on Android.
 
 Here are the dependencies on my pubspec.yaml file:
 
 magic_ext_oauth: ^0.3.0
 magic_sdk: ^4.1.3
 
 I am using Flutter version 3.13.9

**Comment by Ariflo** [comment]
@nziokajimkelly Thank you for bringing this issue to our attention. We are investigating and will report back once we've determined the solution to the error.

**Comment by Ariflo** [comment]
@nziokajimkelly we're unfortunately having trouble reproducing the error you described. Have you tried troubleshooting with [our demo app](https://github.com/magiclabs/magic-flutter/tree/main/magic_demo)? Feel free to test with your Magic API Key and switch to using one of our demo app API Keys: `pk_live_78EABCE90112A046`. As it stands we are capable of logging in successfully w/ Google on iOS. 

![2023-10-30 13 42 00](https://github.com/magiclabs/magic-flutter/assets/13407884/d3c810a1-223e-41d7-ab90-9f131b62fd69)

**Comment by sleepersubject13** [comment]
Hi, @Ariflo, thank you for the quick feedback. I have tried running your example_app, but it is not building. It fails with an error emanating from the `agent_dart` package:

<img width="1433" alt="Screenshot 2023-11-01 at 23 53 40" src="https://github.com/magiclabs/magic-flutter/assets/40268712/159c2727-5b94-4db8-9d9e-7b2817015683">


The behaviour is the same for iOS. I am building with XCode 15.0.1, and flutter version 3.13.9

**Comment by Ariflo** [comment]
@nziokajimkelly thanks for the heads up, we are aware of the [parseErrorData issue](https://github.com/magiclabs/magic-flutter/issues/45) with the latest version Xcode and are working to send up a resolution asap. Will let you know when it's been released.

**Comment by UnderwriterApp** [comment]
Our app is also facing this issue where login on android works but not on ios.

**Comment by g-gandy** [comment]
We also have the same issue, any update here @Ariflo ?

**Comment by Ariflo** [comment]
@nziokajimkelly @UnderwriterApp @g-gandy See my comments here: https://github.com/magiclabs/magic-flutter/issues/45#issuecomment-1802547340. 

We believe the two issues may be related here. As soon as `agent_dart` maintainers release [their fix](https://github.com/AstroxNetwork/agent_dart/commit/2b4c8b975dc12727f85ad2ef3d42f3812a156d8d), we'll release ours. Thank you for your patience.

**Comment by g-gandy** [comment]
Could this issue be affecting log-in across Google and email too? We've got the same issue across both.

**Comment by Ariflo** [comment]
@nziokajimkelly  @UnderwriterApp  @g-gandy the fix for issue https://github.com/magiclabs/magic-flutter/issues/45 has been released in `magic_sdk: ^5.0.0`. Please update your apps to this version and let us know if you continue to see the same error. 

FWIW, we are still able to login successfully via social login with our demo app as originally described in https://github.com/magiclabs/magic-flutter/issues/46#issuecomment-1785978270 above ☝️

**Comment by g-gandy** [comment]
We’re still having the same issue, both on our app m and on a fresh build. @Ariflo @nziokajimkelly anyone else managed to fix this?

**Comment by hbock-42** [comment]
@g-gandy I think my issue https://github.com/magiclabs/magic-flutter/issues/51 might be related to this one.
I had to manually uninstall the application on my phone then reinstall from scratch to solve my issue. Let me know if it works.

I have no idea how I will force my users to do this but at least new users will not have the problem.

**Comment by joshuascan** [comment]
@hbock-42 We had another one of our developers push out a new version of their app without any actual changes. This triggered an update for their users, which cleared their app cache and unblocked them.

The changes also should take affect once the cache clears by itself, but we haven't had any direct confirmation of this. If you find that this is the case for you, please let us know. Thanks!

**Comment by hbock-42** [comment]
@joshuascan We contacted some of our users having this problem and it seems solved, thank you.

Not directly related but very important, when problems occur on the mobile SDK, this is not visible on the status page https://status.magic.link/
This is very problematic as we cannot automatically activate a degraded version of our app when magic has issue.
