### ISSUE TITLE
magic_ext_oidc 0.0.3 Error

### ISSUE THREAD

**Issue by AppleDayali** [magiclabs/magic-flutter#58]
Because magic_ext_oidc 0.0.3 requires SDK version >=3.2.0 <4.0.0 and no versions of magic_ext_oidc match >0.0.3 <0.1.0, magic_ext_oidc ^0.0.3 is forbidden.
So, because qa depends on magic_ext_oidc ^0.0.3, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try using the Flutter SDK version: 3.16.0. 

But,
With flutter 3.16.0, report Error: Type 'DecoderCallback' not found. 
https://github.com/ScerIO/packages.flutter/issues/448

So, I hope you can lower the support version of flutter, thank you very much.

**Comment by Ariflo** [comment]
@AppleDayali Thank you for bringing this to our attention, we will address it asap.

**Comment by romin-halltari** [comment]
@AppleDayali We've released the following versions which should address your issue:
```
magic_sdk: 6.0.1
magic_ext_oauth: 0.4.7
magic_ext_tezos: 0.2.6
magic_ext_solana: 0.3.5
magic_ext_oidc: 0.0.4
```
Thank you for your patience and please let us know if any other issue arises.
