### ISSUE TITLE
non-abstract class 'MagicCredential' is missing implementations for these members:

### ISSUE THREAD

**Issue by anchao-lu** [magiclabs/magic-flutter#6]
Error: The non-abstract class 'MagicCredential' is missing implementations for these members:
../…/web3/magic_credential.dart:9
     - Credentials.signToEcSignature
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.
    class MagicCredential extends CredentialsWithKnownAddress
          ^^^^^^^^^^^^^^^
: Context: 'Credentials.signToEcSignature' is defined here.
../…/credentials/credentials.dart:84
      MsgSignature signToEcSignature(
                   ^^^^^^^^^^^^^^^^^
    Failed to package /Users/monkey/Desktop/Projects/FacePro/main-app.
    Command PhaseScriptExecution failed with a nonzero exit code

**Comment by anchao-lu** [comment]
web3dart wrong

**Comment by anchao-lu** [comment]
web3dart v2.5.1 abstract class Credentials add new method signToEcSignature
MagicCredential needs update

**Comment by Princewil** [comment]
Does this package still works? especially since it shows analysis issues

**Comment by Ethella** [comment]
Thx for reporting this. I'll take a look.
