### ISSUE TITLE
[Support] No version of magic_ext_oauth match on Flutter

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [magiclabs/magic-flutter#8]
## Problem 
I'm using `Flutter 3.7.0-1.2.pre • channel beta`. I want to use login with SMS and Social Login methods. The docs use `magic_sdk` v0.4.0. But it leads to dependency errors.

## Steps to reproduce
1. Add `magic_sdk: ^0.3.0` and `magic_ext_oauth: ^0.1.0` to the pubspec.yaml
2. Run `flutter pub get`
3. Upgrade the magic_sdk to v0.4.0 => `magic_sdk: ^0.4.0`
4. Run `flutter pub get`

## Logs
```
Resolving dependencies...
Because no versions of magic_ext_oauth match >0.1.1 <0.2.0 and magic_ext_oauth <0.1.1 depends on magic_sdk ^0.3.0, magic_ext_oauth <0.1.1-∞ or >0.1.1 <0.2.0 requires magic_sdk ^0.3.0.
And because magic_ext_oauth 0.1.1 depends on magic_sdk ^0.3.1, magic_ext_oauth <0.2.0 requires magic_sdk ^0.3.0.
So, because unito depends on both magic_sdk ^0.4.0 and magic_ext_oauth ^0.1.0, version solving failed.
pub get failed
command: "C:\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "C:\Users\andre\AppData\Local\Pub\Cache",
}
exit code: 1
```

## Things I've already tried
1. Running `flutter clean` and `flutter pub get`
2. Upgrading to `magic_sdk: ^2.0.0` and `magic_ext_oauth: ^1.0.0` but it still leads to error

**Comment by Ethella** [comment]
@AlphaByte-RedTeam I'll take a look into this.
